"""Capture session facts in a journal through code rather than agent behavior.

A client hook invokes this module at session end. The mechanism is independent
of the selected harness, and the agent neither knows about it nor edits the
journal manually. This removes contention around a shared state file.

The capture records facts only: branch and HEAD, commits since the previous
capture, and uncommitted changes. It appends to
``.agent/journal/YYYY-MM-DD.md`` and writes nothing when no facts changed.
Semantic decisions such as a next step remain human-owned.

This implementation is repository-owned shared code.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .fs import atomic_write


def _git(repo_root: Path, *args: str) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=repo_root)
    return proc.stdout.strip() if proc.returncode == 0 else ""


def capture(repo_root: Path) -> Path | None:
    """Capture session facts in the journal, or return None if unchanged."""
    if not (repo_root / ".git").exists():
        return None

    journal_dir = repo_root / ".agent" / "journal"
    journal_dir.mkdir(parents=True, exist_ok=True)
    marker = journal_dir / ".last-capture"  # Runtime marker ignored by journal/.gitignore.

    branch = _git(repo_root, "rev-parse", "--abbrev-ref", "HEAD") or "-"
    head = _git(repo_root, "rev-parse", "HEAD")
    dirty = _git(repo_root, "status", "--porcelain")
    last_head = marker.read_text().strip() if marker.is_file() else ""

    if head == last_head and not dirty:
        return None  # Nothing changed since the previous capture.

    if last_head:
        commits = _git(repo_root, "log", "--oneline", f"{last_head}..{head}")
    else:
        commits = _git(repo_root, "log", "--oneline", "-5")

    now = datetime.now()
    lines = [f"## {now:%H:%M} - branch {branch} @ {head[:9] or '-'}"]
    if commits:
        lines.append("commits since the previous capture:")
        lines += [f"- {c}" for c in commits.splitlines()]
    if dirty:
        files = dirty.splitlines()
        lines.append(f"uncommitted: {len(files)} files")
        lines += [f"- {f.strip()}" for f in files[:15]]
        if len(files) > 15:
            lines.append(f"- ... {len(files) - 15} more")
    diffstat = _git(repo_root, "diff", "--shortstat")
    if diffstat:
        lines.append(f"diff: {diffstat}")
    day_file = journal_dir / f"{now:%Y-%m-%d}.md"
    new_day = not day_file.exists()
    if new_day:
        before = f"# Journal {now:%Y-%m-%d} (generated by session-capture; do not edit)"
    else:
        before = day_file.read_text(encoding="utf-8").rstrip()
    # Blocks have one blank line between them and the file ends with one LF;
    # otherwise git diff --check flags the generated journal after each capture.
    atomic_write(day_file, before + "\n\n" + "\n".join(lines) + "\n")
    marker.write_text(head)
    return day_file


def main() -> int:
    """Resolve the repository root from cwd, falling back to cwd itself.

    Always return exit 0: a failed capture must not fail the client's session
    shutdown.
    """
    root = _git(Path.cwd(), "rev-parse", "--show-toplevel")
    capture(Path(root) if root else Path.cwd())
    return 0


if __name__ == "__main__":
    sys.exit(main())
