"""tool-bridge CLI with eight public operations and one hidden worker."""
from __future__ import annotations

import argparse
import json
import math
import os
import shlex
import shutil
import signal
import stat
import subprocess
import sys
import time
import tomllib
from pathlib import Path
from typing import Any

from .jobs import (
    boot_id,
    cancel_path,
    create_json_once,
    derive_state,
    gc,
    list_jobs,
    new_job,
    now_iso,
    process_group_alive,
    read_proc,
    read_request,
    read_result,
    result_path,
    same_boot_id,
    write_result,
)
from .render import (
    render_log,
    render_result,
    render_status,
    render_wait_timeout,
    result_payload,
    status_payload,
)
from .shared.cliargs import ArgumentParser
from .shared.config import CommonConfigError, load_common_config, tools_data_root
from .shared.fs import atomic_write
from .worker import run_event_hook, worker_main


EXIT_OK = 0
EXIT_QUOTA = 75
EXIT_TRANSIENT = 111
EXIT_FAIL = 1

SECRET_HINTS: tuple[str, ...] = ()
DATA_ENV = "BRIDGE_DATA"
DATA_DIR = "bridge-data"
PUBLIC_COMMANDS = ("run", "wait", "result", "log", "status", "cancel", "doctor", "install")
REPO_ROOT = Path(__file__).resolve().parents[1]
RULE_CONTENT = (
    "# generated by bridge install\n"
    'prefix_rule(pattern=["bridge"], decision="allow")\n'
)
CONFIG_DEFAULTS: dict[str, Any] = {
    "effort": "xhigh",
    "max_retries": 2,
    "backoff": [60, 300],
    "stall_after": 1200,
    "wait_default": 3000,
    "max_time": 5400,
    "gc_days": 14,
    "on_event": "",
    "codex_writable_roots": [],
}


def resolve_home(cli_home: str | None = None) -> Path:
    """Resolve data home in order: CLI, BRIDGE_DATA, TOOLS_DATA, default."""
    raw = cli_home or os.environ.get(DATA_ENV)
    path = Path(raw).expanduser() if raw else tools_data_root() / DATA_DIR
    return path.resolve()


def _bridge_config(home: Path) -> dict[str, Any]:
    path = home / "config.toml"
    if not path.exists() and not path.is_symlink():
        return dict(CONFIG_DEFAULTS)
    try:
        raw = tomllib.loads(path.read_text("utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ValueError(f"{path}: file is not readable: {error}") from error
    unknown = set(raw) - set(CONFIG_DEFAULTS)
    if unknown:
        raise ValueError(f"{path}: unknown fields {sorted(unknown)}")
    result = {**CONFIG_DEFAULTS, **raw}
    if not isinstance(result["effort"], str) or not result["effort"].strip():
        raise ValueError(f"{path}: effort must be a non-empty string")
    for key in ("max_retries", "stall_after", "wait_default", "max_time", "gc_days"):
        if (type(result[key]) not in (int, float) or not math.isfinite(result[key])
                or result[key] < 0):
            raise ValueError(f"{path}: {key} must be a non-negative number")
    if type(result["max_retries"]) is not int:
        raise ValueError(f"{path}: max_retries must be an integer")
    backoff = result["backoff"]
    if not isinstance(backoff, list) or not backoff or any(
            type(item) not in (int, float) or not math.isfinite(item) or item < 0
            for item in backoff):
        raise ValueError(f"{path}: backoff must be a non-empty list of numbers")
    if not isinstance(result["on_event"], str):
        raise ValueError(f"{path}: on_event must be a shell command string")
    if (not isinstance(result["codex_writable_roots"], list) or
            not all(isinstance(x, str) for x in result["codex_writable_roots"])):
        raise ValueError(f"{path}: codex_writable_roots must be a list of strings")
    if any(not Path(item).expanduser().is_absolute()
           for item in result["codex_writable_roots"]):
        raise ValueError(f"{path}: codex_writable_roots must be absolute")
    return result


def _temporary_binary_roots() -> tuple[Path, ...]:
    # Only per-user temporary roots such as $TMPDIR and /var/folders are treated
    # as ephemeral terminal-shim locations. /tmp is intentionally allowed:
    # repositories and worktrees may keep legitimate test fakes there.
    values = [os.environ.get("TMPDIR"), "/var/folders", "/private/var/folders"]
    roots: list[Path] = []
    for value in values:
        if value:
            roots.append(Path(value).expanduser().absolute())
    return tuple(dict.fromkeys(roots))


def _is_temporary_binary(path: Path) -> bool:
    absolute = path.expanduser().absolute()
    resolved = absolute.resolve()
    for root in _temporary_binary_roots():
        if absolute.is_relative_to(root) or resolved.is_relative_to(root.resolve()):
            return True
    return False


def _which_all(command: str) -> list[Path]:
    candidate = Path(command).expanduser()
    if candidate.is_absolute() or candidate.parent != Path("."):
        found = shutil.which(str(candidate))
        return [Path(found).absolute()] if found else []
    paths: list[Path] = []
    for entry in os.environ.get("PATH", os.defpath).split(os.pathsep):
        found = shutil.which(command, path=entry or os.curdir)
        if found:
            absolute = Path(found).absolute()
            if absolute not in paths:
                paths.append(absolute)
    return paths


def _resolve_binary(command: str, *, configured_absolute: bool = False) -> tuple[str, str | None]:
    candidates = _which_all(command)
    if not candidates:
        raise ValueError(f"binary not found: {command}")
    if configured_absolute:
        return str(candidates[0].resolve()), None
    stable = [path for path in candidates if not _is_temporary_binary(path)]
    chosen = stable[0] if stable else candidates[0]
    warning = None
    if not stable:
        warning = (f"only a temporary {command} binary was found: {chosen}; "
                   "retry or resume cannot start after that path disappears")
    return str(chosen.resolve()), warning


def _configured_harness(
    agent: str,
) -> tuple[list[str], str | None, str | None, list[str]]:
    common = load_common_config()
    configured = next((item for item in common.harnesses if item.name == agent), None)
    argv = list(configured.argv) if configured else [agent]
    configured_absolute = configured is not None and Path(argv[0]).expanduser().is_absolute()
    try:
        argv[0], warning = _resolve_binary(argv[0], configured_absolute=configured_absolute)
    except ValueError as error:
        raise ValueError(f"harness binary not found: {argv[0]}") from error
    return argv, configured.model_default if configured else None, \
        configured.effort_default if configured else None, [warning] if warning else []


def _job(home: Path, job_id: str) -> Path:
    if not job_id or Path(job_id).name != job_id or job_id in {".", ".."}:
        raise ValueError("invalid job ID")
    job = home / "jobs" / job_id
    if not job.is_dir():
        raise ValueError(f"unknown job: {job_id}")
    return job


def _read_prompt(args: argparse.Namespace) -> str:
    if bool(args.prompt_file) == bool(args.stdin_source):
        raise ValueError("provide exactly one prompt source: --prompt-file FILE or -")
    if args.prompt_file:
        path = Path(args.prompt_file).expanduser()
        try:
            return path.read_text("utf-8")
        except (OSError, UnicodeError) as error:
            raise ValueError(f"could not read prompt {path}: {error}") from error
    return sys.stdin.read()


def _launcher_content() -> str:
    python = str(Path(sys.executable).resolve())
    root = str(REPO_ROOT)
    return (
        "#!/bin/sh\n"
        f"export PYTHONPATH={shlex.quote(root)}${{PYTHONPATH:+:\"$PYTHONPATH\"}}\n"
        f"exec {shlex.quote(python)} -m tool_bridge \"$@\"\n"
    )


def _install_file(path: Path, content: str, mode: int) -> bool:
    encoded = content.encode("utf-8")
    unchanged = False
    try:
        unchanged = (
            path.is_file() and not path.is_symlink() and path.read_bytes() == encoded and
            stat.S_IMODE(path.stat().st_mode) == mode
        )
    except OSError:
        unchanged = False
    if unchanged:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(path, encoded)
    path.chmod(mode)
    return True


def _find_decision(value: object) -> str | None:
    if isinstance(value, dict):
        decision = value.get("decision")
        if isinstance(decision, str):
            return decision
        for child in value.values():
            found = _find_decision(child)
            if found:
                return found
    if isinstance(value, list):
        for child in value:
            found = _find_decision(child)
            if found:
                return found
    return None


def _check_execpolicy(rule: Path) -> bool:
    codex = shutil.which("codex")
    if not codex:
        print("  execpolicy: Codex not found; check skipped")
        return True
    try:
        checked = subprocess.run(
            [codex, "execpolicy", "check", "--rules", str(rule), "bridge", "status"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as error:
        print("bridge: execpolicy check could not start: " + str(error), file=sys.stderr)
        return False
    output = checked.stdout.strip()
    try:
        decision = _find_decision(json.loads(output)) if output else None
    except json.JSONDecodeError:
        decision = None
    shown = decision or (output.splitlines()[0][:200] if output else "no decision")
    print("  execpolicy decision: " + shown)
    if checked.returncode != 0 or decision != "allow":
        detail = checked.stderr.strip().splitlines()
        if detail:
            print("bridge: execpolicy check: " + detail[-1][:500], file=sys.stderr)
        return False
    return True


def install(args: argparse.Namespace) -> int:
    user_home = Path.home()
    bin_dir = (Path(args.bin_dir).expanduser() if args.bin_dir else
               user_home / ".local" / "bin").resolve()
    artifacts = (
        ("skill claude", REPO_ROOT / "deploy" / "skills" / "claude" / "SKILL.md",
         user_home / ".claude" / "skills" / "bridge" / "SKILL.md", 0o600),
        ("skill codex", REPO_ROOT / "deploy" / "skills" / "codex" / "SKILL.md",
         user_home / ".codex" / "skills" / "bridge" / "SKILL.md", 0o600),
    )
    try:
        for label, source, target, mode in artifacts:
            content = source.read_text("utf-8")
            changed = _install_file(target, content, mode)
            print(f"  {label}: {target} - " + ("updated" if changed else "unchanged"))
        rule = user_home / ".codex" / "rules" / "bridge.rules"
        changed = _install_file(rule, RULE_CONTENT, 0o600)
        print(f"  execpolicy rule: {rule} - " + ("updated" if changed else "unchanged"))
        launcher = bin_dir / "bridge"
        changed = _install_file(launcher, _launcher_content(), 0o755)
        print(f"  launcher: {launcher} - " + ("updated" if changed else "unchanged"))
    except (OSError, UnicodeError) as error:
        print("bridge: installation did not complete: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    checked = _check_execpolicy(rule)
    print('  Claude allow-list: add "Bash(bridge:*)" to permissions.allow in '
          '~/.claude/settings.json manually')
    return EXIT_OK if checked else EXIT_FAIL


def _run(home: Path, args: argparse.Namespace) -> int:
    if os.environ.get("CODEX_SANDBOX"):
        print(
            "bridge run is denied inside CODEX_SANDBOX: invoke the bare bridge name "
            "through execpolicy and pass the prompt with --prompt-file, without a heredoc or pipe",
            file=sys.stderr,
        )
        return EXIT_FAIL
    cwd = Path(args.cwd).expanduser().resolve()
    if not cwd.is_dir():
        print(f"bridge: --cwd does not exist or is not a directory: {cwd}", file=sys.stderr)
        return EXIT_FAIL
    try:
        prompt = _read_prompt(args)
        if not prompt.strip():
            raise ValueError("prompt must not be empty")
        config = _bridge_config(home)
        harness_argv, model_default, effort_default, binary_warnings = \
            _configured_harness(args.agent)
    except (ValueError, CommonConfigError) as error:
        print("bridge: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    max_time = args.max_time if args.max_time is not None else config["max_time"]
    if not math.isfinite(max_time) or max_time <= 0:
        print("bridge: --max-time must be greater than zero", file=sys.stderr)
        return EXIT_FAIL
    mode = "write" if args.write else "read-only"
    roots: list[str] = []
    if mode == "write" and args.agent == "codex":
        candidates = [cwd / ".git", *(Path(item).expanduser() for item in config["codex_writable_roots"])]
        roots = list(dict.fromkeys(str(path.resolve()) for path in candidates))
    effort = args.effort
    if effort is None:
        effort = effort_default
    if effort is None and args.agent == "codex":
        effort = config["effort"]
    model = args.model if args.model is not None else model_default
    request = {
        "agent": args.agent,
        "cwd": str(cwd),
        "mode": mode,
        "model": model,
        "effort": effort,
        "resume_id": args.resume,
        "max_time": max_time,
        "max_retries": config["max_retries"],
        "backoff": config["backoff"],
        "stall_after": config["stall_after"],
        "wait_default": config["wait_default"],
        "on_event": config["on_event"],
        "codex_writable_roots": roots,
        "harness_argv": harness_argv,
        "warnings": binary_warnings,
        "prompt": prompt,
        "created_at": now_iso(),
    }
    gc(home, config["gc_days"])
    try:
        job_id, job = new_job(home, request)
        log_path = home / "logs" / f"worker-{job_id}.log"
        fd = os.open(log_path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
        stream = os.fdopen(fd, "ab", buffering=0)
        try:
            worker_process = subprocess.Popen(
                [sys.executable, "-m", "tool_bridge", "--home", str(home),
                 "_worker", str(job)],
                cwd=str(Path(__file__).resolve().parents[1]),
                stdin=subprocess.DEVNULL,
                stdout=stream,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        finally:
            stream.close()
        handshake_deadline = time.monotonic() + 2
        while not (job / "proc.json").is_file() and not result_path(job).is_file():
            if worker_process.poll() is not None or time.monotonic() >= handshake_deadline:
                break
            time.sleep(0.01)
        if not (job / "proc.json").is_file() and not result_path(job).is_file():
            raise OSError("worker did not publish proc.json")
    except (OSError, ValueError) as error:
        print("bridge: could not start worker: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    if args.wait is None and args.json:
        print(json.dumps({
            "id": job_id,
            "dir": str(job),
            "agent": args.agent,
            "cwd": str(cwd),
            "mode": mode,
        }, ensure_ascii=False))
    elif not args.json:
        print(job_id)
    if args.wait is not None:
        timeout = None if args.wait < 0 else args.wait
        return _wait(job, timeout=timeout, full=args.full, json_output=args.json)
    return EXIT_OK


def _result_exit(result: dict[str, Any]) -> int:
    status = result.get("status")
    if status == "ok":
        return EXIT_OK
    if status == "quota":
        return EXIT_QUOTA
    return EXIT_FAIL


def _wait(
    job: Path, *, timeout: float | None, full: bool, json_output: bool = False,
) -> int:
    if timeout is None:
        try:
            timeout = float(_bridge_config(job.parents[1])["wait_default"])
        except ValueError as error:
            print("bridge: " + str(error), file=sys.stderr)
            return EXIT_FAIL
    if timeout is not None and (not math.isfinite(timeout) or timeout < 0):
        print("bridge: --timeout must be non-negative", file=sys.stderr)
        return EXIT_FAIL
    infinite = timeout == 0
    started = time.monotonic()
    try:
        poll = max(0.01, float(os.environ.get("BRIDGE_POLL", "5")))
    except ValueError:
        poll = 5.0
    while True:
        try:
            state = derive_state(job)
        except (OSError, ValueError, json.JSONDecodeError) as error:
            print("bridge: corrupted job: " + str(error), file=sys.stderr)
            return EXIT_FAIL
        if state["state"] == "finished":
            result = read_result(job)
            output = (json.dumps(result_payload(job, full=full), ensure_ascii=False)
                      if json_output else render_result(job, full=full))
            if output:
                print(output)
            return _result_exit(result)
        if state["state"] == "died":
            if json_output:
                print(json.dumps(result_payload(job, full=full), ensure_ascii=False))
            else:
                print(f"{job.name} died: {state['reason']}")
            return EXIT_FAIL
        if state.get("worker_died"):
            if json_output:
                print(json.dumps(result_payload(job, full=full), ensure_ascii=False))
            else:
                print(render_wait_timeout(job, state))
            return EXIT_TRANSIENT
        if not infinite and time.monotonic() - started >= timeout:
            if json_output:
                print(json.dumps(result_payload(job, full=full), ensure_ascii=False))
            else:
                print(render_wait_timeout(job, state))
            return EXIT_TRANSIENT
        remaining = poll
        if not infinite:
            remaining = min(remaining, max(0.01, timeout - (time.monotonic() - started)))
        time.sleep(remaining)


def _cancel(home: Path, job_id: str) -> int:
    def actual_result() -> int:
        result = read_result(job)
        status = str(result.get("status") or "unknown")
        if status == "cancelled" and result.get("cancelled_by") == "cli":
            print(f"{job_id} cancelled by cli")
            return EXIT_OK
        print(f"{job_id} already finished: {status}")
        return EXIT_FAIL

    try:
        job = _job(home, job_id)
        if result_path(job).is_file():
            return actual_result()
        state = derive_state(job)
        request = read_request(job)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print("bridge: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    if state["state"] != "running":
        terminal = {
            "id": job_id, "status": "died", "reason": state["reason"],
            "exit_code": None, "session_id": None, "attempts": [], "usage": None,
            "warnings": [], "finished_at": now_iso(),
        }
        won = write_result(job, terminal)
        if not won:
            return actual_result()
        run_event_hook(job, request, terminal)
        print(f"{job_id} died")
        return EXIT_FAIL
    marker = {"by": "cli", "at": now_iso()}
    create_json_once(cancel_path(job), marker)
    try:
        proc = read_proc(job)
        pgid = proc.get("pgid")
        stored_boot = proc.get("boot_id")
        current_boot = boot_id()
        boot_mismatch = (stored_boot is not None and current_boot is not None and
                         not same_boot_id(str(stored_boot), current_boot))
        if boot_mismatch or type(pgid) is not int or pgid <= 1:
            raise ValueError("unsafe or stale pgid")
        if pgid == os.getpgrp():
            raise ValueError("worker is in the caller's process group")
        try:
            os.killpg(pgid, signal.SIGTERM)
        except PermissionError:
            os.kill(pgid, signal.SIGTERM)
    except ProcessLookupError:
        if result_path(job).is_file():
            return actual_result()
        terminal = {
            "id": request.get("id") or job_id,
            "status": "died", "reason": "dead-pgid", "exit_code": None,
            "session_id": None, "attempts": [], "usage": None, "warnings": [],
            "finished_at": now_iso(),
        }
        won = write_result(job, terminal)
        if not won:
            return actual_result()
        run_event_hook(job, request, terminal)
        print(f"{job_id} died")
        return EXIT_FAIL
    except (OSError, ValueError, json.JSONDecodeError, RuntimeError) as error:
        print("bridge: cancellation was not sent: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    try:
        grace = max(0.0, float(os.environ.get("BRIDGE_GRACE", "20")))
    except ValueError:
        grace = 20.0
    deadline = time.monotonic() + grace
    while process_group_alive(pgid) and time.monotonic() < deadline:
        time.sleep(0.05)
    if process_group_alive(pgid):
        try:
            os.killpg(pgid, signal.SIGKILL)
        except PermissionError:
            try:
                os.kill(pgid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        except ProcessLookupError:
            pass
    verify_deadline = time.monotonic() + 1
    while process_group_alive(pgid) and time.monotonic() < verify_deadline:
        time.sleep(0.02)
    remnants = process_group_alive(pgid)
    terminal = {
        "id": request.get("id") or job_id,
        "status": "cancelled", "reason": "cli", "cancelled_by": "cli",
        "exit_code": None, "session_id": None, "attempts": [], "usage": None,
        "warnings": [], "finished_at": now_iso(),
    }
    won = write_result(job, terminal)
    if won:
        run_event_hook(job, request, terminal)
    if remnants:
        print(f"bridge: process group {pgid} is still alive", file=sys.stderr)
        return EXIT_FAIL
    return EXIT_OK if won else actual_result()


def _version(command: list[str]) -> str:
    try:
        result = subprocess.run(
            [*command, "--version"], stdin=subprocess.DEVNULL, capture_output=True,
            text=True, timeout=3, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    line = (result.stdout or result.stderr).strip().splitlines()
    return line[0][:120] if line else "unknown"


def _stale_trust_count() -> int | None:
    path = Path.home() / ".codex" / "config.toml"
    if not path.is_file():
        return None
    try:
        raw = tomllib.loads(path.read_text("utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return None
    projects = raw.get("projects")
    if not isinstance(projects, dict):
        return 0
    return sum(1 for name in projects if isinstance(name, str) and not Path(name).exists())


def _file_matches(path: Path, expected: str, *, executable: bool = False) -> bool:
    try:
        return (
            path.is_file() and not path.is_symlink() and
            path.read_text("utf-8") == expected and
            (not executable or bool(path.stat().st_mode & stat.S_IXUSR))
        )
    except (OSError, UnicodeError):
        return False


def doctor(home: Path) -> int:
    """Observe environment, configuration, and derived state without mutation."""
    problems: list[str] = []
    common_path = tools_data_root() / "config.toml"
    common_exists = common_path.exists()
    common = None
    try:
        common = load_common_config()
        common_valid: bool | None = True if common.exists else None
    except CommonConfigError as error:
        common_valid = False
        problems.append("shared config is invalid: " + str(error))
    configured = {item.name: list(item.argv) for item in common.harnesses} if common else {}
    commands: dict[str, list[str] | None] = {}
    binary_warnings: list[str] = []
    for name in ("git", "python3", "codex", "claude"):
        command = configured.get(name, [name])
        try:
            binary, warning = _resolve_binary(
                command[0], configured_absolute=bool(
                    name in configured and Path(command[0]).expanduser().is_absolute()))
            commands[name] = [binary, *command[1:]]
            if warning:
                binary_warnings.append(warning)
        except ValueError:
            commands[name] = None
    problems += ["missing binary " + name for name, command in commands.items()
                 if command is None]
    if not home.is_dir():
        problems.append("missing data home " + str(home) + " (create it with mkdir -p)")
    elif not os.access(home, os.W_OK):
        problems.append("data home is not writable: " + str(home))
    bridge_valid: bool | None = None
    if home.is_dir() and ((home / "config.toml").exists() or (home / "config.toml").is_symlink()):
        try:
            _bridge_config(home)
            bridge_valid = True
        except ValueError as error:
            bridge_valid = False
            problems.append("bridge config is invalid: " + str(error))
    died = stalled = 0
    if home.is_dir():
        for job in list_jobs(home):
            try:
                state = derive_state(job)
            except (OSError, ValueError, json.JSONDecodeError):
                died += 1
                continue
            died += state["state"] == "died"
            stalled += state.get("stalled_min") is not None
    sandbox = bool(os.environ.get("CODEX_SANDBOX") or
                   os.environ.get("CLAUDE_CODE_BASH_SANDBOX_ENABLED"))
    user_home = Path.home()
    rule = Path.home() / ".codex" / "rules" / "bridge.rules"
    rule_ok = _file_matches(rule, RULE_CONTENT)
    skill_states: dict[str, tuple[Path, bool]] = {}
    for agent in ("claude", "codex"):
        source = REPO_ROOT / "deploy" / "skills" / agent / "SKILL.md"
        target = user_home / f".{agent}" / "skills" / "bridge" / "SKILL.md"
        try:
            expected = source.read_text("utf-8")
        except (OSError, UnicodeError):
            expected = ""
        skill_states[agent] = (target, bool(expected) and _file_matches(target, expected))

    default_bin = user_home / ".local" / "bin"
    default_launcher = default_bin / "bridge"
    found_bridge = shutil.which("bridge")
    found_path = Path(found_bridge).resolve() if found_bridge else None
    if default_launcher.is_file():
        launcher = default_launcher
    elif found_path is not None:
        launcher = found_path
    else:
        launcher = default_launcher
    launcher_ok = _file_matches(launcher, _launcher_content(), executable=True)
    launcher_on_path = bool(
        launcher_ok and found_path is not None and found_path == launcher.resolve()
    )
    path_dirs = {
        Path(item or os.curdir).expanduser().resolve()
        for item in os.environ.get("PATH", os.defpath).split(os.pathsep)
    }
    if not launcher_ok:
        problems.append("bridge launcher is missing or differs: " + str(launcher))
    elif not launcher_on_path:
        problems.append("bridge launcher is not first in PATH: " + str(launcher))
    if default_launcher.is_file() and default_bin.resolve() not in path_dirs:
        problems.append(str(default_bin) + " is not in PATH")
    if not rule_ok:
        problems.append("execpolicy rule is missing or differs: " + str(rule))
    for agent, (path, valid) in skill_states.items():
        if not valid:
            problems.append(f"{agent} skill is missing or differs: {path}")
    stale_trust = _stale_trust_count()

    print("bridge doctor: " + ("OK" if not problems else "NOT OK"))
    print("  tools: " + ", ".join(
        f"{name}=" + ((command[0] + " (" + _version(command) + ")")
                      if command else "MISSING")
        for name, command in commands.items()))
    print("  home: " + str(home) + ("" if home.is_dir() else " (missing)"))
    print("  shared config: path=" + str(common_path)
          + " exists=" + str(common_exists).lower()
          + " valid=" + ("-" if common_valid is None else str(common_valid).lower())
          + " error=" + str(common_valid is False).lower())
    print("  bridge config: " + ("-" if bridge_valid is None else str(bridge_valid).lower()))
    print(f"  jobs: died={died} stalled={stalled}")
    print("  sandbox: " + ("active" if sandbox else "not detected"))
    print("  launcher: " + str(launcher)
          + (" (in PATH, matches)" if launcher_on_path else
             " (matches, not in PATH)" if launcher_ok else " (missing or differs)"))
    print("  execpolicy rule: " + str(rule)
          + (" (matches)" if rule_ok else " (missing or differs)"))
    print("  skills: " + ", ".join(
        f"{agent}=" + ("matches" if valid else "missing or differs")
        for agent, (_path, valid) in skill_states.items()
    ))
    print("  stale trust: " + ("unknown" if stale_trust is None else str(stale_trust)))
    for warning in binary_warnings:
        print("  warning: " + warning)
    for problem in problems:
        print("  problem: " + problem)
    return EXIT_OK if not problems else EXIT_FAIL


def _parser() -> ArgumentParser:
    common = ArgumentParser(add_help=False)
    common.add_argument(
        "--home", metavar="DIR", default=argparse.SUPPRESS,
        help="data directory; overrides BRIDGE_DATA and TOOLS_DATA",
    )
    parser = ArgumentParser(
        prog="bridge", description="Detached Claude and Codex jobs",
        parents=[common],
    )
    sub = parser.add_subparsers(
        dest="cmd", required=True,
        metavar="{" + ",".join(PUBLIC_COMMANDS) + "}",
    )

    run = sub.add_parser(
        "run", help="create and start a job",
        description="Create a job; read the prompt only from a file or stdin (-).",
        parents=[common])
    run.add_argument("--agent", choices=("codex", "claude"), required=True,
                     help="harness that will perform the work")
    run.add_argument("--cwd", metavar="DIR", required=True,
                     help="existing harness working directory")
    run.add_argument("--write", action="store_true",
                     help="allow constrained writes; read-only by default")
    run.add_argument("--model", metavar="MODEL",
                     help="select a model instead of the harness default")
    run.add_argument("--effort", metavar="LEVEL",
                     help="select reasoning effort")
    run.add_argument("--resume", metavar="ID",
                     help="resume a thread/session ID in a new job")
    run.add_argument("--max-time", metavar="S", type=float,
                     help="maximum wall time for the entire job in seconds")
    run.add_argument("--wait", metavar="S", nargs="?", type=float, const=-1.0,
                     help="wait for a result; omit S for wait_default, use 0 forever")
    run.add_argument("--full", action="store_true",
                     help="do not apply the 12k output cap while waiting")
    run.add_argument("--json", action="store_true",
                     help="print the created job as JSON")
    run.add_argument("--prompt-file", metavar="FILE",
                     help="read the prompt from a UTF-8 file")
    run.add_argument("stdin_source", metavar="-", nargs="?", choices=("-",),
                     help="'-' reads the prompt from stdin through EOF")

    wait = sub.add_parser("wait", help="wait for a terminal result",
                          description="Wait for an existing job to finish.",
                          parents=[common])
    wait.add_argument("id", metavar="ID", help="job ID")
    wait.add_argument("--timeout", metavar="S", type=float,
                      help="wait timeout; omit for wait_default, use 0 forever")
    wait.add_argument("--full", action="store_true",
                      help="do not apply the 12k output cap")

    result = sub.add_parser("result", help="show the saved response",
                            description="Show job state and its saved response.",
                            parents=[common])
    result.add_argument("id", metavar="ID", help="job ID")
    result.add_argument("--full", action="store_true",
                        help="do not apply the 12k output cap")
    result.add_argument("--json", action="store_true",
                        help="print state, result, and artifact paths as JSON")

    log = sub.add_parser("log", help="show the event stream",
                         description="Show the combined event stream for all job attempts.",
                         parents=[common])
    log.add_argument("id", metavar="ID", help="job ID")
    log.add_argument("--tail", metavar="N", type=int,
                     help="last N lines; 0 means the full log")
    log.add_argument("--raw", action="store_true",
                     help="show raw JSONL events without rendering")

    status = sub.add_parser("status", help="show derived state",
                            description="Show one job or all jobs.",
                            parents=[common])
    status.add_argument("id", metavar="ID", nargs="?",
                        help="one job ID; omit to show all jobs")
    status.add_argument("--json", action="store_true",
                        help="print machine-readable state as JSON")

    cancel = sub.add_parser("cancel", help="stop a job process group",
                            description="Cancel a live job and its entire process group.",
                            parents=[common])
    cancel.add_argument("id", metavar="ID", help="job ID to cancel")
    sub.add_parser("doctor", help="diagnose without mutation",
                   description="Inspect the environment and jobs without changes.",
                   parents=[common])
    install_parser = sub.add_parser(
        "install", help="install launcher, skills, and execpolicy rule",
        description="Idempotently install bridge-owned integration files.",
        parents=[common])
    install_parser.add_argument(
        "--bin-dir", metavar="DIR",
        help="launcher directory instead of ~/.local/bin")

    worker = sub.add_parser("_worker", parents=[common])
    worker.add_argument("job_dir")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    home = resolve_home(getattr(args, "home", None))
    if args.cmd == "_worker":
        return worker_main(args.job_dir)
    if args.cmd == "doctor":
        return doctor(home)
    if args.cmd == "install":
        return install(args)
    if args.cmd == "run":
        return _run(home, args)
    try:
        if args.cmd == "wait":
            return _wait(_job(home, args.id), timeout=args.timeout, full=args.full)
        if args.cmd == "result":
            job = _job(home, args.id)
            if args.json:
                print(json.dumps(result_payload(job, full=args.full), ensure_ascii=False))
            else:
                print(render_result(job, full=args.full))
            return EXIT_OK
        if args.cmd == "log":
            if args.tail is not None and args.tail < 0:
                raise ValueError("--tail must be non-negative")
            print(render_log(_job(home, args.id), tail=args.tail, raw=args.raw))
            return EXIT_OK
        if args.cmd == "status":
            jobs = [_job(home, args.id)] if args.id else list_jobs(home)
            if args.json:
                payload = []
                for job in jobs:
                    try:
                        payload.append(status_payload(job))
                    except (OSError, ValueError, json.JSONDecodeError) as error:
                        payload.append({"id": job.name, "state": "broken",
                                        "reason": str(error)})
                print(json.dumps(payload[0] if args.id else payload, ensure_ascii=False))
            else:
                for job in jobs:
                    try:
                        print(render_status(job))
                    except (OSError, ValueError, json.JSONDecodeError) as error:
                        detail = str(error).replace("\n", " ")
                        print(f"{job.name} broken {detail}")
            return EXIT_OK
        if args.cmd == "cancel":
            return _cancel(home, args.id)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print("bridge: " + str(error), file=sys.stderr)
        return EXIT_FAIL
    return EXIT_FAIL


if __name__ == "__main__":
    sys.exit(main())
