"""Shared behavior for hermetic Codex and Claude CLI fakes."""
from __future__ import annotations

import json
import os
import signal
import sys
import time
from pathlib import Path


def _write(path_name: str, value: str) -> None:
    path = os.environ.get(path_name)
    if path:
        Path(path).write_text(value, "utf-8")


def _append(path_name: str, value: object) -> None:
    path = os.environ.get(path_name)
    if path:
        with Path(path).open("a", encoding="utf-8") as stream:
            stream.write(json.dumps(value, ensure_ascii=False) + "\n")


def _counter() -> int:
    raw = os.environ.get("FAKE_COUNTER")
    if not raw:
        try:
            return int(os.environ.get("BRIDGE_ATTEMPT", "1"))
        except ValueError:
            return 1
    path = Path(raw)
    try:
        value = int(path.read_text("ascii")) + 1
    except (OSError, ValueError):
        value = 1
    path.write_text(str(value), "ascii")
    return value


def _emit(value: dict) -> None:
    print(json.dumps(value, ensure_ascii=False), flush=True)


def _codex_started(thread_id: str) -> None:
    _emit({"type": "thread.started", "thread_id": thread_id})


def _claude_started(session_id: str) -> None:
    _emit({"type": "system", "subtype": "init", "session_id": session_id})


def _last_path(argv: list[str]) -> Path | None:
    try:
        return Path(argv[argv.index("-o") + 1])
    except (ValueError, IndexError):
        return None


def _session(agent: str, argv: list[str]) -> str:
    flag = "resume" if agent == "codex" else "--resume"
    try:
        return argv[argv.index(flag) + 1]
    except (ValueError, IndexError):
        return "fake-thread" if agent == "codex" else "fake-session"


def _ok(agent: str, session_id: str, argv: list[str], text: str = "ok") -> int:
    if agent == "codex":
        _emit({"type": "turn.started"})
        _emit({"type": "item.completed", "item": {
            "type": "agent_message", "text": text,
        }})
        _emit({"type": "turn.completed", "usage": {
            "input_tokens": 3, "output_tokens": 1,
        }})
        target = _last_path(argv)
        if target:
            target.write_text(text, "utf-8")
    else:
        _emit({"type": "assistant", "session_id": session_id, "message": {
            "content": [{"type": "text", "text": text}],
            "usage": {"input_tokens": 3, "output_tokens": 1},
        }})
        _emit({"type": "result", "subtype": "success", "result": text,
               "session_id": session_id, "is_error": False,
               "usage": {"input_tokens": 3, "output_tokens": 1}})
    return 0


def main(agent: str) -> int:
    argv = sys.argv[1:]
    if "--version" in argv:
        print(f"fake-{agent} 1.0")
        return 0
    if agent == "codex" and argv[:2] == ["execpolicy", "check"]:
        _append("FAKE_SEEN_EXECPOLICY", argv)
        try:
            rule = Path(argv[argv.index("--rules") + 1]).read_text("utf-8")
            command = argv[argv.index("--rules") + 2:]
        except (OSError, ValueError, IndexError):
            rule = ""
            command = []
        expected = (
            "# generated by bridge install\n"
            'prefix_rule(pattern=["bridge"], decision="allow")\n'
        )
        decision = "allow" if rule == expected and command[:1] == ["bridge"] else "prompt"
        print(json.dumps({"decision": decision}, ensure_ascii=False))
        return 0
    if os.environ.get("FAKE_MODE") == "ignore-term":
        signal.signal(signal.SIGTERM, signal.SIG_IGN)
    prompt = sys.stdin.read()
    _write("FAKE_SEEN_PROMPT", prompt)
    _append("FAKE_SEEN_ARGV", argv)
    env_target = os.environ.get("FAKE_SEEN_ENV")
    if env_target:
        Path(env_target).write_text(json.dumps(dict(os.environ), sort_keys=True), "utf-8")

    mode = os.environ.get("FAKE_MODE", "ok")
    count = _counter()
    session_id = _session(agent, argv)
    if mode == "die-early" and count == 1:
        print("process disappeared before session start", file=sys.stderr, flush=True)
        return 1

    if agent == "codex":
        _codex_started(session_id)
    else:
        _claude_started(session_id)

    if mode == "capacity-then-ok" and count == 1:
        if agent == "codex":
            _emit({"type": "error", "message": "model at capacity"})
        else:
            _emit({"type": "result", "subtype": "error", "result": "model at capacity",
                   "session_id": session_id, "is_error": True})
        return 1
    if mode == "active-writer":
        if agent == "codex":
            _emit({"type": "turn.failed", "error": {
                "message": "already has an active writer"}})
        else:
            _emit({"type": "result", "subtype": "error",
                   "result": "already has an active writer",
                   "session_id": session_id, "is_error": True})
        return 1
    if mode in {"capacity-then-ok", "die-early"}:
        return _ok(agent, session_id, argv)
    if mode == "limit-text-ok":
        return _ok(agent, session_id, argv, "usage limit reached, resets at midnight")
    if mode == "recovered-stream":
        if agent == "codex":
            _emit({"type": "error", "message": "stream disconnected", "codex_error_info": {
                "code": "response_stream_disconnected"}})
        return _ok(agent, session_id, argv, "recovered")
    if mode == "quota":
        if agent == "codex":
            _emit({"type": "turn.failed", "error": {"message": "usage limit exceeded",
                   "codex_error_info": {"code": "usage_limit_exceeded"}}})
        else:
            _emit({"type": "result", "subtype": "error", "result": "Claude usage limit reached",
                   "session_id": session_id, "is_error": True})
        return 1
    if mode in {"permanent", "cyber"}:
        code = "bad_request" if mode == "permanent" else "cyber_policy"
        message = "model is not supported" if mode == "permanent" else "flagged for possible cybersecurity risk"
        if agent == "codex":
            _emit({"type": "turn.failed", "error": {"message": message,
                   "codex_error_info": {"code": code}}})
        else:
            _emit({"type": "result", "subtype": code, "result": message,
                   "session_id": session_id, "is_error": True})
        print(message, file=sys.stderr, flush=True)
        return 1
    if mode == "write-then-fail":
        if agent == "codex":
            _emit({"type": "item.completed", "item": {
                "type": "file_change", "changes": [{"path": "changed.txt"}],
            }})
            _emit({"type": "turn.failed", "error": {"message": "unknown failure"}})
        else:
            _emit({"type": "assistant", "session_id": session_id, "message": {
                "content": [{"type": "tool_use", "name": "Write", "input": {}}],
            }})
            _emit({"type": "result", "subtype": "error", "result": "unknown failure",
                   "session_id": session_id, "is_error": True})
        return 1
    if mode == "denied":
        print("writing outside of the project was denied", file=sys.stderr, flush=True)
        return _ok(agent, session_id, argv)
    if mode == "successful-denied-output":
        if agent == "codex":
            _emit({"type": "item.completed", "item": {
                "type": "command_execution",
                "command": "read docs",
                "exit_code": 0,
                "aggregated_output": "docs say writing outside of the project was denied",
            }})
        return _ok(agent, session_id, argv)
    if mode in {"slow", "ignore-term"}:
        time.sleep(float(os.environ.get("FAKE_SLEEP", "60")))
        return _ok(agent, session_id, argv)
    if mode == "hang":
        while True:
            time.sleep(1)
    if mode == "long":
        return _ok(agent, session_id, argv, "x" * 30_000)
    return _ok(agent, session_id, argv)
